// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The installed Prisma CLI (7.9.1) does not honor a separate `directUrl` here —
    // it only ever connects via `url` for validate/migrate/generate. Supabase's
    // transaction pooler doesn't support the advisory locks migrate needs (it hangs
    // indefinitely), so CLI tooling uses the direct connection (DIRECT_URL).
    // The app's own Prisma Client (lib/prisma.ts, prisma/seed.ts) constructs its
    // adapter directly from DATABASE_URL (transaction pooler) and is unaffected by
    // this file — that's the correct connection for runtime queries.
    url: env("DIRECT_URL"),
  },
});
